### ISSUE TITLE
[Feature Request] Add ability to sort notebooks

### ISSUE THREAD

**Issue by CodeCubeNeo** [quillpad/quillpad#184]
Maybe just how they are displayed in the left sidebar (sorted by name, date...?).

**Comment by groaking** [comment]
I've been waiting for this feature.
Notebook sorting is certainly something I need for my **Quillnote** setup, because I have a lot of notebooks with numerical prefixes. It's funny to have notebook `#20` before notebook `#7`.

But after a year since this issue was posted, nobody seems to work on this issue.

Notebook sorting is related to tag sorting (see #44). I think we need to have both notebook and tag sortings in the next release of Quillnote.
