### ISSUE TITLE
Provide more info when Nextcloud sync fails to connect

### ISSUE THREAD

**Issue by hamoid** [quillpad/quillpad#259]
The error message `Something went wrong` shown in a Toast at
https://github.com/quillpad/quillpad/blob/master/app/src/main/java/org/qosp/notes/ui/sync/nextcloud/NextcloudAccountDialog.kt#L68
does not include details about what went wrong. This is not ideal to help find out a solution.

It would be very useful to either show the `result` in the toast or send it to the log to help diagnose the problem.

**Comment by nofishonfriday** [comment]
@hamoid I added this. You can try the test APK here and let me know if it helps:
https://github.com/quillpad/quillpad/actions/runs/9006051675/artifacts/1485063847

**Comment by hamoid** [comment]
Thank for this! Are my notes kept if I install the apk?

**Comment by nofishonfriday** [comment]
> Are my notes kept if I install the apk?
If you installed from F-Droid, they sign the apks with their own keys, so you couldn't do an 'update' with this apk (because of key mismatch), so no.
Not sure if the build artefacts are signed with the same key as the Google Play version (@jsixface?).
Anyway, since my PR is already merged into master and if you're not in a hurry you could also wait until next official release and let me know then (not sure when that'll happen though).

**Comment by jsixface** [comment]
It's a good habit to take a backup of the notes before every update. 
Yes. Both the Google play and f-droid versions are signed using the same key. 
I'll do a Google play release this weekend.
